### ISSUE TITLE
Code formatter and license

### ISSUE THREAD

**Issue by michaelhglass** [felixreimann/jreliability#14]
- Application of the Opt4J-style code formatter across the project
- Typo in license (mentions Opt4J instead of JRealibility)

**Comment by felixreimann** [comment]
Could we also create a test that every commited Java file starts with this static license header? Should be a simple test in gradle but something easily overseen...

**Comment by michaelhglass** [comment]
The license plugin automatically adds the licenseCheck to the check environment as documented here:
> Also it will add the licenseCheck task to the check lifecycle task dependencies, so that during a regular build any missing headers are flagged.
https://github.com/hierynomus/license-gradle-plugin
Unfortunately, it adds it to the build task and not "only" to the check. Thus, the dependsOn statement can be removed. Adding it solely to the check task may require to adapt the plugin which I think is not worth the effort. If you disagree, please comment on the issue.

**Comment by felixreimann** [comment]
we can close this one now, right?
