### ISSUE TITLE
org.jreliability.function.common.ReliabilityFunctionType never used

### ISSUE THREAD

**Issue by felixreimann** [felixreimann/jreliability#2]
Is it still used? Someone thinks we need this?
@michaelhglass could you check this please?

**Comment by michaelhglass** [comment]
I will check why this artifact made it to the main branch. If I remember correctly, this was used as part of a Bachelor's thesis to model distributions of failure rates and not single values. The work eventually ended up much later in this: Khosravi F., Glaß M., Teich J.: Automatic Reliability Analysis in the Presence of Probabilistic Common Cause Failures. In: IEEE Transactions on Reliability 66 (2017), S. 319-338, ISSN: 0018-9529, DOI: 10.1109/TR.2016.2638320.
I'll remove it from the current master and we should again discuss when integrating the interval-based calculations.
